### PR TITLE
Layer builder performance improvements

### PR DESCRIPTION
**Pull request by chuckdumont**
Avoid multiple concurrent builders for same layer when cache key generator has not yet been created.

### CODE REVIEW

**Comment by chuckdumont** [comment]
@ddumont - please review

**Comment by ddumontatibm** [comment]
lgtm

**Comment by ddumontatibm** [comment]
Are you expecting permanent deadlock with the threads waiting on that mutex?   The logging is ok but won't help the thread die if they get stuck.   Should we have a max wait?

**Comment by chuckdumont** [comment]
The logging is only for diagnostic purposes.  I certainly don't expect deadlocks, but I think that it's just good programming practice to provide logging if a thread seems to be stuck in an indefinite wait.

**Comment by ddumontatibm** [comment]
Well I don't think it's a good idea to explode the logs with messages about it.
If all threads deadlock we'll have n messages logged every 30 seconds until the server is restarted.

**Comment by chuckdumont** [comment]
And we'll know why the server died instead of not having any information at all.

**Comment by ddumontatibm** [comment]
I'm not asking you to take the logging out.   I'm asking if it's worth having a max wait time on the lock before we let the thread die.

**Comment by chuckdumont** [comment]
OK.  An exception will be thrown after 15 minutes now.

**Comment by ddumontatibm** [comment]
lgtm

**Pull request merged**
