### PR TITLE
URLConverter is unreliable on Domino

### PR DESCRIPTION
**Pull request by chuckdumont**

### CODE REVIEW

**Comment by chuckdumont** [comment]
@ddumont Please review

**Comment by chuckdumont** [comment]
@ddumont, please review

**Comment by ddumontatibm** [comment]
so we don't hit this on domino, what does that mean?

**Comment by ddumontatibm** [comment]
We'll just get a reference to it from the context each time we need it instead of saving it?

**Comment by chuckdumont** [comment]
Without the URLConverter service reference, we won't use the URLConverter at all.  So all access to resources in bundles will be made through the OSGi bundle api rather than the file system.  This might have some performance implications, and I don't know if it will resolve the bundle extraction problems we're seeing on Domino, but it's worth a shot.

**Comment by ddumontatibm** [comment]
Hmm...   We can try it but I'm not very hopeful.

**Comment by chuckdumont** [comment]
Merged.  Please create a snapshot so I can run tests.

**Pull request merged**
